"""Per-user PDF password store for chat attachment decryption.

Some PDF sources (Israeli payslips, employer Form 106s, municipal documents
generated by iText) ship "secured" — they open silently in Adobe Reader /
Chrome because viewers cache or bypass the owner password, but pypdf,
pikepdf, PyMuPDF, and PDFium all refuse to extract content without the
actual password. claude.exe in turn emits a placeholder response and
exits 1, killing the advisor turn.

To handle the common case where a household has a small set of recurring
passwords (typically the recipients' national ID numbers), each user can
keep a JSON file at::

    ${ARGOSY_HOME}/configs/<user_id>/pdf_passwords.json

containing the candidate passwords. On encrypted upload, Argosy tries each
in turn; on success, the PDF is re-serialized without encryption and
proceeds through the catalog as if it had been plain all along.

File schema (gitignored; lives under `configs/<user_id>/` which the
top-level `.gitignore` excludes by default)::

    {
      "_note": "Each entry is a candidate password Argosy will try on encrypted PDFs.",
      "passwords": [
        "066067216",
        "061279766"
      ]
    }

Best-effort everywhere: missing file → empty list → encrypted PDFs are
rejected with the existing AttachmentEncryptedError pointing at the
Print-to-PDF workaround. Malformed JSON → same outcome plus a warning log.
"""

from __future__ import annotations

import json
from io import BytesIO
from pathlib import Path

from argosy.config import get_settings
from argosy.logging import get_logger

log = get_logger(__name__)


def _config_path(user_id: str) -> Path:
    """Resolve `${ARGOSY_HOME}/configs/<user_id>/pdf_passwords.json`."""
    home = Path(get_settings().home)
    return home / "configs" / user_id / "pdf_passwords.json"


def load_pdf_passwords(user_id: str) -> list[str]:
    """Load the candidate password list for a user. Returns [] when absent.

    Accepts two shapes for tolerance:
      * `{"passwords": ["p1", "p2"]}` — preferred, matches the documented schema.
      * `["p1", "p2"]` — a bare list at the top level, also accepted.

    Any other shape, missing file, or JSON parse error returns [] (with a
    WARNING log on parse errors). The encrypted-PDF flow then falls through
    to the existing rejection path, so the upload doesn't crash silently.
    """
    p = _config_path(user_id)
    if not p.exists():
        return []
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        log.warning(
            "pdf_passwords.load_failed",
            path=str(p),
            error=f"{type(exc).__name__}: {exc}",
        )
        return []

    raw_list: list = []
    if isinstance(data, dict) and isinstance(data.get("passwords"), list):
        raw_list = data["passwords"]
    elif isinstance(data, list):
        raw_list = data

    return [str(p) for p in raw_list if isinstance(p, (str, int)) and str(p)]


def try_decrypt_pdf(raw_bytes: bytes, passwords: list[str]) -> bytes | None:
    """Attempt to decrypt an encrypted PDF using the candidate passwords.

    Tries each password in order. On the first success, re-serializes
    the PDF with pypdf's PdfWriter so the output has no /Encrypt entry
    and any downstream consumer (Anthropic's PDF parser, claude.exe,
    further pypdf passes) reads it as plain content. Returns the
    unencrypted bytes; or None if no password worked, the file isn't
    a parseable PDF, or pypdf raised an unexpected error during the
    re-serialization step.

    Owner-password matches (`decrypt()` returns 2) are accepted the
    same as user-password matches — both give full content access for
    re-serialization purposes.
    """
    if not passwords:
        return None

    # Local import — keeps the module importable even in environments where
    # pypdf hasn't been installed (test fixtures, doc builds).
    try:
        from pypdf import PdfReader, PdfWriter
        from pypdf.errors import PdfReadError
    except ImportError:
        log.warning("pdf_passwords.pypdf_missing")
        return None

    try:
        reader = PdfReader(BytesIO(raw_bytes))
    except PdfReadError as exc:
        log.warning(
            "pdf_passwords.read_failed",
            error=f"{type(exc).__name__}: {exc}",
        )
        return None

    if not reader.is_encrypted:
        # Caller mistakenly handed us a plain PDF. Return it unchanged
        # rather than running it through the writer (which would mutate
        # producer metadata for no reason).
        return raw_bytes

    for password in passwords:
        try:
            result = reader.decrypt(password)
        except Exception as exc:  # noqa: BLE001 — pypdf raises various
            log.warning(
                "pdf_passwords.decrypt_raised",
                error=f"{type(exc).__name__}: {exc}",
            )
            continue
        if result == 0:
            # 0 = password rejected; try the next candidate.
            continue
        # 1 = user password matched, 2 = owner password matched.
        # Both unlock content for re-serialization.
        try:
            writer = PdfWriter()
            for page in reader.pages:
                writer.add_page(page)
            out = BytesIO()
            writer.write(out)
            unencrypted = out.getvalue()
            log.info(
                "pdf_passwords.decrypted",
                decrypt_result=result,
                input_bytes=len(raw_bytes),
                output_bytes=len(unencrypted),
            )
            return unencrypted
        except Exception as exc:  # noqa: BLE001 — pypdf write paths
            log.warning(
                "pdf_passwords.write_failed",
                error=f"{type(exc).__name__}: {exc}",
            )
            return None

    return None


__all__ = ["load_pdf_passwords", "try_decrypt_pdf"]
