"""Wave 5 — Advisor chat upload helper.

The advisor chat accepts file attachments alongside the text message
(text/markdown documents, images, and PDFs). This module:
  - Saves each upload to `<ARGOSY_HOME>/uploads/<user_id>/<turn_uuid>/`
  - Classifies MIME → kind ("text" | "image" | "pdf")
  - Rejects unsupported MIMEs with a 415-friendly exception

PDFs are forwarded to the Anthropic API as native `document` content
blocks (vs. server-side text extraction). This preserves layout,
tables, and embedded images, and lets Claude OCR scanned PDFs — the
"accuracy over LLM cost" binding rule in CLAUDE.md.

Size limits (hardcoded module constants below; not yet plumbed through
`argosy.toml`):
  - per file: 10 MB (`MAX_BYTES_PER_FILE`)
  - per turn: 20 MB total (`MAX_BYTES_PER_TURN`)

Spec: docs/superpowers/specs (Wave 5 inline; SDD §6.14).
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Literal

from fastapi import HTTPException, UploadFile
from pydantic import BaseModel

from argosy.config import get_settings
from argosy.logging import get_logger

log = get_logger(__name__)


# Per-file and per-turn size caps (bytes). See module docstring.
MAX_BYTES_PER_FILE = 10 * 1024 * 1024  # 10 MB
MAX_BYTES_PER_TURN = 20 * 1024 * 1024  # 20 MB


# NTFS forbids these in filenames; ext4/APFS tolerate most but `:` is still
# special on macOS (HFS resource fork). Replace with `_` so an upload from
# a quirky source doesn't 500 on Windows or silently corrupt on macOS.
_ILLEGAL_FILENAME_CHARS = '<>:"|?*\x00'


def _sanitize_filename(name: str) -> str:
    """Strip directory components AND replace OS-illegal chars with `_`."""
    base = os.path.basename(name) or "attachment"
    return "".join("_" if c in _ILLEGAL_FILENAME_CHARS else c for c in base)


_TEXT_MIMES = {
    "text/plain",
    "text/markdown",
    "text/x-markdown",
    "application/json",
    "application/x-yaml",
    "text/yaml",
    "text/csv",
    "text/tab-separated-values",
}
_IMAGE_MIMES = {
    "image/png",
    "image/jpeg",
    "image/jpg",
    "image/webp",
    "image/gif",
}
_PDF_MIMES = {"application/pdf", "application/x-pdf"}
_TEXT_EXTS = {".md", ".markdown", ".txt", ".text", ".yaml", ".yml", ".json", ".csv", ".tsv"}
_IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif"}
_PDF_EXTS = {".pdf"}


class Attachment(BaseModel):
    """A single saved upload from a chat turn."""

    kind: Literal["text", "image", "pdf"]
    path: str
    mime_type: str
    original_name: str
    size_bytes: int


class AttachmentTooLargeError(HTTPException):
    """HTTP 413 — file exceeds size cap."""

    def __init__(self, detail: str) -> None:
        super().__init__(status_code=413, detail=detail)


class AttachmentUnsupportedError(HTTPException):
    """HTTP 415 — MIME type or extension not allowed."""

    def __init__(self, detail: str) -> None:
        super().__init__(status_code=415, detail=detail)


class AttachmentEncryptedError(HTTPException):
    """HTTP 422 — PDF has encryption that blocks programmatic extraction.

    The PDF has an `/Encrypt` entry in its trailer dict. Many real-world
    "secured" PDFs (notably Israeli payslips generated by iText, and
    similar municipal/employer documents) carry an encryption dict that
    restricts editing/printing/copying via the owner password but is
    silently bypassed by interactive PDF viewers (Adobe Reader, Chrome,
    Edge, browser viewers) for VIEWING — so users typically don't see a
    password prompt and assume the PDF is unprotected.

    Programmatic extractors don't get the same free pass: pypdf,
    `claude.exe`, and Anthropic's server-side PDF parser all refuse to
    extract content without the owner password. claude.exe specifically
    returns a placeholder "PDF is password protected" assistant message
    and then exits with code 1; the SDK turns that exit code into a
    fatal `ProcessError`, so even the placeholder is discarded.

    Detecting at upload time gives a clear, actionable error instead of
    a 5-second wait + opaque SDK crash. The standard workaround works
    on every viewer: File → Print → "Save as PDF" / "Microsoft Print
    to PDF". The reprinted copy has no encryption dict.
    """

    def __init__(self, detail: str) -> None:
        super().__init__(status_code=422, detail=detail)


def _is_pdf_encrypted(raw_bytes: bytes) -> bool:
    """Return True if the PDF has an `/Encrypt` entry in its trailer dict.

    Two-stage check to balance speed against precision:

    1. Fast byte scan for ``/Encrypt`` in the first + last 64 KB of the
       file. If absent, definitely not encrypted — return False without
       paying the PDF-parsing cost. This is the hot path for the typical
       Argosy upload (statements, Form 106, plan documents, screenshots).

    2. If the byte scan matches, confirm with pypdf's
       ``PdfReader.is_encrypted`` to avoid a false positive when the
       literal bytes ``/Encrypt`` happen to appear in an unencrypted
       content stream (very rare, but theoretically possible). pypdf
       parses the trailer dict properly and only returns True when an
       actual ``/Encrypt`` reference is present in the document trailer.

    If pypdf itself throws on the file (malformed PDF, unsupported
    variant), we fall back to the byte-scan result — rejecting an
    upload Anthropic likely couldn't read anyway is the safer default.
    """
    head = raw_bytes[:65_536]
    tail = raw_bytes[-65_536:] if len(raw_bytes) > 65_536 else b""
    if b"/Encrypt" not in head and b"/Encrypt" not in tail:
        return False
    try:
        from io import BytesIO

        from pypdf import PdfReader

        return PdfReader(BytesIO(raw_bytes)).is_encrypted
    except Exception:  # noqa: BLE001 — any pypdf failure → byte-scan wins
        return True


def _classify(mime_type: str, original_name: str) -> Literal["text", "image", "pdf"]:
    """Map MIME + extension → 'text' | 'image' | 'pdf'. Raise 415 otherwise."""
    mt = (mime_type or "").lower().strip()
    ext = Path(original_name or "").suffix.lower()

    if mt in _IMAGE_MIMES or mt.startswith("image/") or ext in _IMAGE_EXTS:
        return "image"
    if mt in _PDF_MIMES or ext in _PDF_EXTS:
        return "pdf"
    if mt in _TEXT_MIMES or mt.startswith("text/") or ext in _TEXT_EXTS:
        return "text"
    raise AttachmentUnsupportedError(
        f"unsupported attachment type: mime={mt!r} ext={ext!r}; "
        "accepted: text/markdown, images, PDFs"
    )


def _uploads_root(user_id: str, turn_uuid: str) -> Path:
    """`<ARGOSY_HOME>/uploads/<user_id>/<turn_uuid>/` — created on demand."""
    home = Path(get_settings().home)
    root = home / "uploads" / user_id / turn_uuid
    root.mkdir(parents=True, exist_ok=True)
    return root


async def save_attachment(
    *, user_id: str, turn_uuid: str, upload: UploadFile,
) -> Attachment:
    """Persist a single FastAPI UploadFile and return its typed Attachment.

    Wave A (provenance): the body of this function now flows through
    ``argosy.services.file_catalog.catalog_upload``. The catalog handles
    sha256-based dedup, the new date-organized storage layout, audit
    emission, and DB row insertion. The ``Attachment`` shape returned
    here is preserved so Wave-5 callers don't break.

    Raises:
        AttachmentTooLargeError: file > MAX_BYTES_PER_FILE
        AttachmentUnsupportedError: MIME/extension not in allowlist
    """
    # Local import — avoids a circular at module load (file_catalog imports
    # this module's `_sanitize_filename`).
    from argosy.services.file_catalog import catalog_upload

    original_name = upload.filename or "attachment"
    mime_type = upload.content_type or "application/octet-stream"
    kind = _classify(mime_type, original_name)

    # Stream-read so we can short-circuit on size.
    contents = await upload.read()
    size = len(contents)
    if size > MAX_BYTES_PER_FILE:
        raise AttachmentTooLargeError(
            f"attachment {original_name!r} is {size} bytes; cap is {MAX_BYTES_PER_FILE}"
        )

    # Handle encrypted PDFs. Anthropic's PDF parser refuses any PDF
    # with an /Encrypt dict, even when the encryption only restricts
    # permissions (print/copy/edit) and is bypassed by interactive
    # viewers for VIEWING. Without intervention the user gets a 5-second
    # wait + opaque "Command failed exit 1" because claude.exe emits a
    # placeholder "PDF is password protected" message then exits 1.
    #
    # First try per-user password rules at
    # ${ARGOSY_HOME}/configs/<user_id>/pdf_passwords.json — if any of
    # them decrypts the file, transparently replace `contents` with the
    # unencrypted re-serialization and continue. Otherwise fall back to
    # the explicit AttachmentEncryptedError so the user sees the
    # Print-to-PDF workaround. See `argosy/services/pdf_passwords.py`.
    if kind == "pdf" and _is_pdf_encrypted(contents):
        from argosy.services.pdf_passwords import (
            load_pdf_passwords,
            try_decrypt_pdf,
        )

        decrypted = try_decrypt_pdf(contents, load_pdf_passwords(user_id))
        if decrypted is not None:
            contents = decrypted
            size = len(contents)
        else:
            raise AttachmentEncryptedError(
                f"{original_name!r} has PDF encryption that blocks the AI "
                "from reading it. Israeli payslips (תלוש שכר), Form 106s "
                "from some employers, and similar 'secured' documents open "
                "in Adobe / Chrome without prompting for a password, but "
                "the encryption dict in the file still blocks programmatic "
                "extraction (yours, Argosy's, and Anthropic's). Workaround "
                "options: (1) add the password to "
                "${ARGOSY_HOME}/configs/<user_id>/pdf_passwords.json so "
                "Argosy can decrypt server-side automatically next time, "
                "or (2) open the PDF, choose File → Print → 'Microsoft "
                "Print to PDF' (or 'Save as PDF' in macOS Preview), save "
                "the reprinted copy, and upload that instead."
            )

    dto = await catalog_upload(
        user_id=user_id,
        raw_bytes=contents,
        original_name=original_name,
        mime_type=mime_type,
        kind=kind,
        source="chat_attachment",
        turn_uuid=turn_uuid,
    )
    log.info(
        "turn_attachment.saved",
        user_id=user_id,
        turn_uuid=turn_uuid,
        kind=kind,
        size_bytes=size,
        original_name=original_name,
        catalog_file_id=dto.id,
    )
    return Attachment(
        kind=kind,
        path=dto.storage_path,
        mime_type=mime_type,
        original_name=original_name,
        size_bytes=size,
    )


async def save_attachments_with_total_cap(
    *, user_id: str, turn_uuid: str, uploads: list[UploadFile],
) -> list[Attachment]:
    """Save many; enforce the per-turn cap on the running total."""
    saved: list[Attachment] = []
    running = 0
    for u in uploads:
        att = await save_attachment(user_id=user_id, turn_uuid=turn_uuid, upload=u)
        running += att.size_bytes
        if running > MAX_BYTES_PER_TURN:
            # Roll back files written so far so a partial-save doesn't leak.
            for prior in saved + [att]:
                try:
                    Path(prior.path).unlink(missing_ok=True)
                except Exception:  # noqa: BLE001
                    pass
            raise AttachmentTooLargeError(
                f"turn attachments total {running} bytes exceeds cap {MAX_BYTES_PER_TURN}"
            )
        saved.append(att)
    return saved


__all__ = [
    "Attachment",
    "AttachmentEncryptedError",
    "AttachmentTooLargeError",
    "AttachmentUnsupportedError",
    "MAX_BYTES_PER_FILE",
    "MAX_BYTES_PER_TURN",
    "save_attachment",
    "save_attachments_with_total_cap",
]
