"use client";

/**
 * Wave 8 v2 polish — bilingual Full Plan narrative.
 *
 * Replaces the engineer-style horizon_*_md dump in the recap's "Full
 * plan" card with a five-section, plain-English story written by the
 * PlanNarrativeAgent. Includes a language toggle so the user can read
 * the same content in Hebrew. Falls back to the structured horizon
 * markdown when the narrative endpoint hasn't generated a payload
 * yet (e.g. agent failure / cold cache + slow first request).
 */

import { useEffect, useState } from "react";

import { Markdown } from "@/components/markdown";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { api, type DraftResponse, type PlanNarrativeResponseDTO } from "@/lib/api";

type Lang = "en" | "he";

interface FullPlanNarrativeProps {
  userId: string;
  // Fallback horizon markdown when the narrative endpoint is still
  // generating (first request can take ~30s as the agent runs).
  structured: DraftResponse | null;
  rawMarkdown: string;
}

export function FullPlanNarrative({
  userId,
  structured,
  rawMarkdown,
}: FullPlanNarrativeProps) {
  const [data, setData] = useState<PlanNarrativeResponseDTO | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [lang, setLang] = useState<Lang>("en");

  useEffect(() => {
    let cancelled = false;
    // eslint-disable-next-line react-hooks/set-state-in-effect -- justified: fetch-on-mount fan-out, same pattern as the /plan page's refresh effect; migrating to use() + Suspense is a separate rewrite.
    setLoading(true);
    setError(null);
    api
      .planCurrentNarrative(userId)
      .then((r) => {
        if (cancelled) return;
        setData(r);
      })
      .catch((e: unknown) => {
        if (cancelled) return;
        setError(e instanceof Error ? e.message : String(e));
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [userId]);

  const refresh = () => {
    setLoading(true);
    setError(null);
    api
      .planCurrentNarrative(userId, true)
      .then((r) => setData(r))
      .catch((e: unknown) =>
        setError(e instanceof Error ? e.message : String(e)),
      )
      .finally(() => setLoading(false));
  };

  const fallback = renderFallback(structured, rawMarkdown);

  return (
    <Card>
      <CardHeader>
        <div className="flex items-start justify-between gap-3">
          <div>
            <CardTitle>Full plan, in plain English</CardTitle>
            <CardDescription>
              A five-section walkthrough: what the plan is, the
              assumptions it rests on, why it&apos;s structured this
              way, what changes when, and how it gets you to
              retirement. Switch the language if you want to read in
              Hebrew.
            </CardDescription>
          </div>
          <div className="flex flex-col items-end gap-2">
            <div className="flex gap-1">
              <LangToggle lang={lang} setLang={setLang} />
            </div>
            <Button
              size="sm"
              variant="outline"
              onClick={refresh}
              disabled={loading}
              className="text-xs"
            >
              {loading ? "Regenerating…" : "Regenerate"}
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {error ? (
          <p className="text-sm text-error font-mono mb-3">{error}</p>
        ) : null}
        {data ? (
          <article
            className="prose prose-sm dark:prose-invert max-w-none"
            // Hebrew uses RTL; let the browser handle bidi via the
            // dir attribute on the wrapper.
            dir={lang === "he" ? "rtl" : "ltr"}
          >
            <Markdown>
              {lang === "he" ? data.narrative_md_he : data.narrative_md_en}
            </Markdown>
            <p className="text-[10px] text-muted-foreground mt-4 not-prose">
              <Badge variant="outline" className="text-[10px] mr-1">
                {data.confidence}
              </Badge>
              Generated by the plan-narrator agent · plan_version{" "}
              #{data.plan_version_id}
            </p>
          </article>
        ) : loading ? (
          <p className="text-sm text-muted-foreground">
            Writing the plan narrative — this runs once per plan (can take a
            minute or two) and is then saved, so future visits load instantly.
          </p>
        ) : fallback ? (
          <>
            <p className="text-xs text-muted-foreground mb-3">
              Narrative unavailable — showing the synthesizer&apos;s
              structured markdown as a fallback.
            </p>
            {fallback}
          </>
        ) : (
          <p className="text-sm text-muted-foreground">
            No plan content available.
          </p>
        )}
      </CardContent>
    </Card>
  );
}

function LangToggle({
  lang,
  setLang,
}: {
  lang: Lang;
  setLang: (l: Lang) => void;
}) {
  return (
    <div className="inline-flex rounded-md border border-border/60 overflow-hidden text-xs font-mono">
      <button
        type="button"
        onClick={() => setLang("en")}
        className={
          lang === "en"
            ? "px-2 py-1 bg-primary text-primary-foreground"
            : "px-2 py-1 hover:bg-muted/50"
        }
      >
        EN
      </button>
      <button
        type="button"
        onClick={() => setLang("he")}
        className={
          lang === "he"
            ? "px-2 py-1 bg-primary text-primary-foreground"
            : "px-2 py-1 hover:bg-muted/50"
        }
      >
        עברית
      </button>
    </div>
  );
}

function renderFallback(
  structured: DraftResponse | null,
  rawMarkdown: string,
): React.ReactNode {
  const horizons: Array<{ title: string; md: string | null | undefined }> = [
    { title: "Long horizon", md: structured?.horizon_long_md },
    { title: "Medium horizon", md: structured?.horizon_medium_md },
    { title: "Short horizon", md: structured?.horizon_short_md },
  ];
  const withContent = horizons.filter(
    (h) => h.md != null && h.md.trim() !== "",
  );
  if (withContent.length > 0) {
    return (
      <div className="flex flex-col gap-4">
        {withContent.map((h) => (
          <section key={h.title}>
            <h3 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground mb-1">
              {h.title}
            </h3>
            <Markdown>{h.md as string}</Markdown>
          </section>
        ))}
      </div>
    );
  }
  if (rawMarkdown) return <Markdown>{rawMarkdown}</Markdown>;
  return null;
}
