"""
md_to_docx.py — Convert a markdown deliverable to Word with a simple text header.

Converts markdown to docx via pandoc, then post-processes via python-docx:
  1. Inject a simple text header ("Generated by <APP_NAME> v<VERSION>").
  2. Format tables: explicit column widths + 9pt font (so they don't render
     as 1-character-wide columns when one cell has long text).
  3. Auto-promote wide tables (>5 columns or any cell >300 chars) into their
     own landscape section, so the table gets ~9 inches of horizontal space
     instead of ~6.5 inches in portrait Letter.

Usage:
    python md_to_docx.py <input.md> [--output <output.docx>]
                                    [--app-name <name>] [--version <version>]
                                    [--no-header]

Defaults: app-name "Argosy", version "0.1.0", header injected.

Requires: pandoc (on PATH), python-docx (pip install python-docx)
"""

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

from docx import Document
from docx.shared import Pt, Cm, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import qn, nsdecls


# --- Page geometry constants (Letter, dxa = twentieths of a point) ----------
LETTER_W_DXA = 12240          # 8.5 in
LETTER_H_DXA = 15840          # 11 in
MARGIN_LEFT_DXA = 1440        # 1 in
MARGIN_RIGHT_DXA = 1440       # 1 in
PORTRAIT_TEXT_DXA = LETTER_W_DXA - MARGIN_LEFT_DXA - MARGIN_RIGHT_DXA   # 9360
LANDSCAPE_TEXT_DXA = LETTER_H_DXA - MARGIN_LEFT_DXA - MARGIN_RIGHT_DXA  # 12960
MIN_COL_DXA = 800             # ~0.55 in — anything narrower truncates words

# --- Wide-table thresholds --------------------------------------------------
WIDE_NCOLS_THRESHOLD = 5            # >5 columns -> landscape
WIDE_CELL_CHARS_THRESHOLD = 300     # any cell with >300 chars of content -> landscape


def _table_cell_text(cell) -> str:
    """Concatenate all text inside a docx table cell."""
    return "\n".join(p.text for p in cell.paragraphs)


def _is_wide_table(table) -> bool:
    """Decide whether a table needs landscape orientation."""
    ncols = len(table.columns)
    if ncols > WIDE_NCOLS_THRESHOLD:
        return True
    for row in table.rows:
        for cell in row.cells:
            if len(_table_cell_text(cell)) > WIDE_CELL_CHARS_THRESHOLD:
                return True
    return False


def _compute_column_widths(table, available_dxa: int) -> list[int]:
    """Distribute `available_dxa` across columns proportional to longest cell length.

    Each column gets at least MIN_COL_DXA. Weights are clamped to [20, 80] so a
    single huge cell doesn't starve every other column.
    """
    ncols = len(table.columns)
    weights = []
    for col_idx in range(ncols):
        max_len = 0
        for row in table.rows:
            try:
                cell_text = _table_cell_text(row.cells[col_idx])
            except IndexError:
                cell_text = ""
            if len(cell_text) > max_len:
                max_len = len(cell_text)
        weights.append(max(20, min(80, max_len if max_len > 0 else 20)))

    total_weight = sum(weights)
    raw_widths = [int(available_dxa * w / total_weight) for w in weights]

    # Enforce minimum column width by stealing from the widest column.
    for i, w in enumerate(raw_widths):
        if w < MIN_COL_DXA:
            deficit = MIN_COL_DXA - w
            raw_widths[i] = MIN_COL_DXA
            widest = max(range(ncols), key=lambda j: raw_widths[j])
            raw_widths[widest] -= deficit

    return raw_widths


def _apply_column_widths(table, widths_dxa: list[int]):
    """Set explicit column widths via tblGrid + per-cell tcW.

    Word ignores `table.columns[i].width` unless we also fix the table layout
    to "fixed" (not auto-fit). Doing both belt-and-braces.
    """
    tbl = table._tbl

    # 1) Force fixed layout (otherwise Word auto-resizes columns).
    tblPr = tbl.tblPr if tbl.tblPr is not None else tbl.get_or_add_tblPr()
    existing_layout = tblPr.find(qn("w:tblLayout"))
    if existing_layout is not None:
        tblPr.remove(existing_layout)
    layout = OxmlElement("w:tblLayout")
    layout.set(qn("w:type"), "fixed")
    tblPr.append(layout)

    # 2) Make the table width = sum of column widths (not 100% of page).
    existing_w = tblPr.find(qn("w:tblW"))
    if existing_w is not None:
        tblPr.remove(existing_w)
    tblW = OxmlElement("w:tblW")
    tblW.set(qn("w:w"), str(sum(widths_dxa)))
    tblW.set(qn("w:type"), "dxa")
    tblPr.append(tblW)

    # 3) Rebuild tblGrid with explicit widths.
    existing_grid = tbl.find(qn("w:tblGrid"))
    if existing_grid is not None:
        tbl.remove(existing_grid)
    grid = OxmlElement("w:tblGrid")
    for w in widths_dxa:
        gc = OxmlElement("w:gridCol")
        gc.set(qn("w:w"), str(w))
        grid.append(gc)
    # tblGrid must come right after tblPr.
    tblPr_idx = list(tbl).index(tblPr)
    tbl.insert(tblPr_idx + 1, grid)

    # 4) Set per-cell width (tcW) so cells honor the column width.
    for row in table.rows:
        for col_idx, cell in enumerate(row.cells):
            if col_idx >= len(widths_dxa):
                continue
            tcPr = cell._tc.get_or_add_tcPr()
            existing_tcW = tcPr.find(qn("w:tcW"))
            if existing_tcW is not None:
                tcPr.remove(existing_tcW)
            tcW = OxmlElement("w:tcW")
            tcW.set(qn("w:w"), str(widths_dxa[col_idx]))
            tcW.set(qn("w:type"), "dxa")
            tcPr.append(tcW)


def _shrink_table_font(table, point_size: int = 9):
    """Set every run inside the table to the given point size (Calibri)."""
    for row in table.rows:
        for cell in row.cells:
            for para in cell.paragraphs:
                for run in para.runs:
                    run.font.size = Pt(point_size)
                    if not run.font.name:
                        run.font.name = "Calibri"


def _make_sectPr(orient: str = "portrait") -> "OxmlElement":
    """Build a <w:sectPr> for a Letter page in the given orientation."""
    if orient == "landscape":
        w, h = LETTER_H_DXA, LETTER_W_DXA  # swap
    else:
        w, h = LETTER_W_DXA, LETTER_H_DXA

    sectPr = OxmlElement("w:sectPr")

    pgSz = OxmlElement("w:pgSz")
    pgSz.set(qn("w:w"), str(w))
    pgSz.set(qn("w:h"), str(h))
    if orient == "landscape":
        pgSz.set(qn("w:orient"), "landscape")
    sectPr.append(pgSz)

    pgMar = OxmlElement("w:pgMar")
    pgMar.set(qn("w:top"), "1440")
    pgMar.set(qn("w:right"), str(MARGIN_RIGHT_DXA))
    pgMar.set(qn("w:bottom"), "1440")
    pgMar.set(qn("w:left"), str(MARGIN_LEFT_DXA))
    pgMar.set(qn("w:header"), "720")
    pgMar.set(qn("w:footer"), "720")
    pgMar.set(qn("w:gutter"), "0")
    sectPr.append(pgMar)

    return sectPr


def _wrap_table_in_landscape_section(table):
    """Insert section breaks before and after `table` so the table renders on
    landscape pages while the rest of the document stays portrait.

    OOXML model: a <w:sectPr> lives inside the <w:pPr> of the LAST paragraph of
    its section. To create a 3-section sandwich (portrait | landscape | portrait):

      ...portrait body...
      <w:p>...</w:p>                    <- last portrait paragraph; we attach
                                            sectPr(portrait) to terminate section 1
      <w:tbl>...</w:tbl>                <- the wide table (now in section 2)
      <w:p><w:pPr><w:sectPr orient=landscape/></w:pPr></w:p>   <- terminator for section 2
      ...portrait body continues...
      <document-final sectPr portrait>

    The trailing portrait sectPr already exists at the end of <w:body> from
    pandoc; we don't touch it.
    """
    tbl = table._tbl
    body = tbl.getparent()

    # Find the paragraph immediately before this table.
    table_idx = list(body).index(tbl)
    prev_p = None
    for i in range(table_idx - 1, -1, -1):
        sibling = body[i]
        if sibling.tag == qn("w:p"):
            prev_p = sibling
            break

    # If there's no preceding paragraph (table is first), create one.
    if prev_p is None:
        prev_p = OxmlElement("w:p")
        body.insert(table_idx, prev_p)
        table_idx += 1

    # Attach a portrait sectPr to the previous paragraph (terminates portrait section).
    pPr = prev_p.find(qn("w:pPr"))
    if pPr is None:
        pPr = OxmlElement("w:pPr")
        prev_p.insert(0, pPr)
    # Drop any existing sectPr in this pPr first (avoid duplicates).
    existing = pPr.find(qn("w:sectPr"))
    if existing is not None:
        pPr.remove(existing)
    pPr.append(_make_sectPr("portrait"))

    # Insert a paragraph AFTER the table that carries the landscape sectPr
    # (terminates the landscape section, after which the document-final
    # portrait sectPr at end of body takes over).
    closer_p = OxmlElement("w:p")
    closer_pPr = OxmlElement("w:pPr")
    closer_pPr.append(_make_sectPr("landscape"))
    closer_p.insert(0, closer_pPr)
    # Insert right after the table.
    body.insert(table_idx + 1, closer_p)


def format_tables(doc: Document) -> tuple[int, int]:
    """Apply column widths + 9pt font to every table.

    Wide tables (>5 cols or any cell >300 chars) are wrapped in a landscape
    section so they get ~9.0 in instead of ~6.5 in of horizontal space.

    Returns (n_portrait, n_landscape).
    """
    n_portrait = 0
    n_landscape = 0

    # Snapshot the list of tables — we don't add tables, only wrap them with
    # sibling paragraphs, so iteration is stable. But process in REVERSE order
    # so paragraph insertions for later tables don't shift the indices of
    # tables we haven't processed yet.
    tables = list(doc.tables)

    for table in reversed(tables):
        wide = _is_wide_table(table)
        if wide:
            available = LANDSCAPE_TEXT_DXA
            _wrap_table_in_landscape_section(table)
            n_landscape += 1
        else:
            available = PORTRAIT_TEXT_DXA
            n_portrait += 1

        widths = _compute_column_widths(table, available)
        _apply_column_widths(table, widths)
        _shrink_table_font(table, point_size=9)

    return n_portrait, n_landscape


def inject_simple_header(
    doc_path: Path, app_name: str, version: str
) -> tuple[int, int]:
    """Open the pandoc-generated docx, format tables, inject a simple text header.

    Header format: "Generated by <app_name> v<version>" — single-line, light
    gray, with a thin bottom rule. No avatar / no logo / no marketing strapline.

    Returns (n_portrait_tables, n_landscape_tables) for caller reporting.
    """
    doc = Document(str(doc_path))

    # Format content tables BEFORE adding the header table — so the header
    # table (1x1, borderless, fixed-width) is not affected by the generic
    # column-width / font logic.
    n_portrait, n_landscape = format_tables(doc)

    # Insert header as the first element: a 1x1 borderless table so it's a
    # discrete band at the top with a thin underline, not a body paragraph.
    table = doc.add_table(rows=1, cols=1)
    table.autofit = True

    body = doc.element.body
    table_element = table._tbl
    body.remove(table_element)
    body.insert(0, table_element)

    cell = table.cell(0, 0)
    para = cell.paragraphs[0]
    para.alignment = WD_ALIGN_PARAGRAPH.LEFT

    run = para.add_run("Generated by ")
    run.font.name = "Calibri"
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    run = para.add_run(app_name)
    run.font.name = "Calibri"
    run.font.size = Pt(10)
    run.bold = True
    run.font.color.rgb = RGBColor(0x0E, 0xA5, 0xE9)  # Argosy primary blue

    run = para.add_run(f" v{version}")
    run.font.name = "Calibri"
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    # Borderless box with a thin gray bottom rule.
    tbl = table._tbl
    tblPr = tbl.tblPr if tbl.tblPr is not None else tbl._add_tblPr()
    borders = tblPr.find(qn("w:tblBorders"))
    if borders is not None:
        tblPr.remove(borders)
    no_borders = parse_xml(
        f'<w:tblBorders {nsdecls("w")}>'
        f'  <w:top w:val="none" w:sz="0" w:space="0"/>'
        f'  <w:left w:val="none" w:sz="0" w:space="0"/>'
        f'  <w:bottom w:val="single" w:sz="4" w:space="0" w:color="CCCCCC"/>'
        f'  <w:right w:val="none" w:sz="0" w:space="0"/>'
        f'  <w:insideH w:val="none" w:sz="0" w:space="0"/>'
        f'  <w:insideV w:val="none" w:sz="0" w:space="0"/>'
        f'</w:tblBorders>'
    )
    tblPr.append(no_borders)

    # Spacer paragraph after the header.
    spacer = doc.add_paragraph()
    spacer.paragraph_format.space_before = Pt(2)
    spacer.paragraph_format.space_after = Pt(2)
    spacer_element = spacer._element
    body.remove(spacer_element)
    body.insert(1, spacer_element)

    doc.save(str(doc_path))
    return n_portrait, n_landscape


def main():
    parser = argparse.ArgumentParser(
        description="Convert markdown to a Word document with a simple app-name header"
    )
    parser.add_argument("input", help="Input markdown file")
    parser.add_argument("--output", "-o", help="Output docx file (default: same name + .docx)")
    parser.add_argument("--app-name", default="Argosy",
                        help="Header brand text (default: Argosy)")
    parser.add_argument("--version", default="0.1.0",
                        help="Version string shown after the app name (default: 0.1.0)")
    parser.add_argument("--no-header", action="store_true",
                        help="Skip header injection; only run pandoc + table formatting")
    args = parser.parse_args()

    input_path = Path(args.input).resolve()
    if not input_path.exists():
        print(f"Error: {input_path} not found", file=sys.stderr)
        sys.exit(1)

    output_path = (
        Path(args.output).resolve() if args.output else input_path.with_suffix(".docx")
    )

    # Step 1: Pandoc conversion (markdown -> docx with embedded images)
    print(f"Converting: {input_path.name} -> {output_path.name}")
    resource_path = str(input_path.parent)
    cmd = [
        "pandoc", str(input_path),
        "-o", str(output_path),
        "--from", "markdown",
        "--to", "docx",
        "--highlight-style", "tango",
        f"--resource-path={resource_path}",
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Pandoc error: {result.stderr}", file=sys.stderr)
        sys.exit(1)

    # Step 2: Inject header + format tables (or just format tables when --no-header)
    if args.no_header:
        doc = Document(str(output_path))
        n_portrait, n_landscape = format_tables(doc)
        doc.save(str(output_path))
    else:
        print(f"Injecting header: {args.app_name} v{args.version}")
        n_portrait, n_landscape = inject_simple_header(
            output_path, args.app_name, args.version
        )

    file_size = output_path.stat().st_size
    print(f"Saved: {output_path} ({file_size // 1024}KB)")
    if n_portrait or n_landscape:
        print(f"Tables formatted: {n_portrait} portrait, {n_landscape} landscape")


if __name__ == "__main__":
    main()
